### ISSUE TITLE
Fix `get_relative_call_site` after the split

### ISSUE THREAD

**Issue by ravwojdyla** [related-sciences/articat#12]
`get_relative_call_site` needs a fix after the split, specifically `get_root_path` doesn't resolve to the root anymore. Instead of being "smart", let's just capture FQ path to the call site module.

**Comment by dhimmel** [comment]
> specifically get_root_path doesn't resolve to the root anymore

Is that because articat cannot figure out which repository is using artecat when it is called? Or that doing so would be error prone?

**Comment by ravwojdyla** [comment]
@dhimmel yea, exactly. It's *definitely possible to do it in some cases, but I'm not sure if I see the value, and I actually see some benefits of recording FQ file path, specifically you can see which file exactly was used.

\* we could use, `git rev-parse --show-toplevel` which would give us the git root (in most cases), but even then, artifact doesn't have a requirement to run within some git repo, so this would fail sometimes (which arguable we already do for git stats #11).

Any opinions?

**Comment by dhimmel** [comment]
I see value in both the fully qualified and relative paths. FQ works all the time, relative works most of the time.

The use case here that I'm most excited about is the ability to have the catalog link to source code on GitHub, and that use case is easier with a relative path.

So perhaps both could be recorded.

**Comment by ravwojdyla** [comment]
@dhimmel sounds good, let's open an issue to do a best effort relative path capture along the FQ path.
