### ISSUE TITLE
Hide `FutureWarning` from papermill

### ISSUE THREAD

**Issue by ravwojdyla** [related-sciences/articat#30]
> /Users/rav/opt/miniconda3/envs/tr-dev-new/lib/python3.9/site-packages/papermill/iorw.py:50: FutureWarning: pyarrow.HadoopFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
  from pyarrow import HadoopFileSystem

**Comment by dhimmel** [comment]
Fixed by https://github.com/nteract/papermill/pull/615 / https://github.com/nteract/papermill/commit/e2f23caa8e427dee272cc602ef914bb9d29cd5ec but no release since Mar 9, 2021.

**Comment by dhimmel** [comment]
Opened an issue for a new papermill release in https://github.com/nteract/papermill/issues/642

**Comment by ravwojdyla** [comment]
Closing this, issue was resolved upstream.
